name: Build svg2gcode-cli

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get stable release date
        id: stable-date
        run: echo "date=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml | grep '^date' -m1 | cut -d'"' -f2)" >> $GITHUB_OUTPUT
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-${{ steps.stable-date.outputs.date }}
          components: rustfmt
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Fmt
        run: cargo +nightly-${{ steps.stable-date.outputs.date }} fmt --check -p svg2gcode-cli
      - name: Clippy
        run: cargo clippy -p svg2gcode-cli -- -D warnings
      - name: Build
        run: cargo build -p svg2gcode-cli
