name: Check svg2gcode-web
on:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get stable release date
        id: stable-date
        run: echo "date=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml | grep '^date' -m1 | cut -d'"' -f2)" >> $GITHUB_OUTPUT
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-${{ steps.stable-date.outputs.date }}
          components: rustfmt
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy
      - name: Fmt
        run: cargo +nightly-${{ steps.stable-date.outputs.date }} fmt --check -p svg2gcode-web
      - name: Clippy
        run: cargo clippy -p svg2gcode-web --target wasm32-unknown-unknown -- -D warnings
      - name: Check
        run: cargo check -p svg2gcode-web --target wasm32-unknown-unknown
